### ISSUE TITLE
Feature Request: Remove Hard coded values on Travis "SonarCloud Addon"

### ISSUE THREAD

**Issue by edumco** [bonigarcia/webdrivermanager#471]
The actual travis configuration has hard coded values that makes the build break in the forked repositories. 

Although using safe encrypted keys, config values should be passed via environment variables so the build become fully reusable.

I forked the repo and created the solution

```
sonarcloud:
        organization: $(SONARCLOUD_ORGANIZATION)
        token:
            secure: $(SONAR_TOKEN)
```

But I did not create the pull request because it would break the build without configuring the variables on your TravisCI account.

- `SONARCLOUD_ORGANIZATION`
- `SONAR_TOKEN`
- `WDM_GITHUBTOKENNAME`
- `WDM_GITHUBTOKENSECRET`

These variables should be described on Readme too!
